name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and tag the Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/feishu-bot
        docker build . --file Containerfile --tag $IMAGE_NAME:latest

    - name: Push Docker image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/feishu-bot
        docker push $IMAGE_NAME:latest
